# Ceci est la partie 0 des TPs d'OASIS.
Le but de cette partie est de se familiariser avec les formats de données de Python et de savoir utiliser ce langage de programmation pour mettre en pratique ce qui aura été vu en cours.

 La première cellule qui se trouve ci-dessous ne contient que des imports de librairies utiles dans les TP. Il faut l'executer sans réfléchir à son contenu.


 Pour réaliser cette partie de manière utile, il suffit de lire le texte en préambule avant chaque cellule et réfléchir au code et comprendre comment le code a produit le résultat affiché.

 Cette partie 0 vous prendra entre 30 et 45 minutes. Il est important de comprendre le fonctionnement de toutes les cellules (sauf la première)


In [1]:
import numpy as np
import simpleaudio as sa
from IPython.display import Audio,display
import sys
import tempfile
import IPython
from skimage.transform import rescale
import matplotlib.pyplot as plt
import subprocess
import scipy.io as io
import scipy
# simplification de certains noms.
pi=np.pi
sin=np.sin
exp=np.exp
cos=np.cos
log=np.log


def joue_son(s,Fe=44100):
  """Joue un son et tient compte de la variable globale Notebook
   Le son est normalisé et joué à la fréquence d'échantillonnage Fe qui vaut
   44100 par défaut."""
  if len(s.shape)>1:
    print("joue_son erreur: Le son n'est pas mono!")
    return
  son=s.copy().astype(np.float32)
  sm=(abs(son)).max()
  if sm==0:
    print("Attention: son uniformément nul!")
  else:
    son/=sm # normalisation
    son=son*(2**15-1)
  son=son.astype(np.uint16)
  play_obj = sa.play_buffer(son, 1, 2, Fe)
  play_obj.wait_done()


def viewimage(im, normalize=True,zoom=1,order=0,titre='',displayfilename=False):
    imin=im.copy().astype(np.float32)
    if len(im.shape)>2:
      imin = rescale(imin, zoom, order=order, channel_axis=2)
    else:
      imin = rescale(imin, zoom, order=order)
    if normalize:
        imin-=imin.min()
        if imin.max()>0:
            imin/=imin.max()
    else:
        imin=imin.clip(0,255)/255
    imin=(imin*255).astype(np.uint8)
    filename=tempfile.mktemp(titre+'.png')
    if displayfilename:
        print (filename)
    plt.imsave(filename, imin, cmap='gray')
    IPython.display.display(IPython.display.Image(filename))

def charge_image(fich):
    a=np.float32(plt.imread(fich))
    return a


def lire_fichier_son(fichier):
  f=io.wavfile.read(fichier)
  if len(f[1].shape)>1:
    out=f[1][:,0] #pas de stereo
  else:
    out=f[1]
  Fe=f[0]
  return (out,Fe) # renvoie un canal sonore (pas de   stereo) et la Freq. d'echant. Fe

lien_donnees=None# "https://www.telecom-paris.fr/perso/~ladjal/donnees_tp1_oasis.tgz"
fichier="donnees_tp1_oasis.tgz"
repdonnees="donnees_tp1_oasis/"
if not (lien_donnees is None):
  subprocess.run(["wget","-O",fichier,lien_donnees])
  subprocess.run(["tar","-xvzf",fichier])



# Ici on voit les définitions de tableaux
Le texte commenté décrit le code en-dessous de lui

In [2]:
# creation d'un tableau de zéros Il a 5 lignes et 6 colonnes (noter le couple de tauille (5,6))
m0=np.zeros((5,6))
print('Le tableau m0 entier: premiere version\n',m0)
# On accède à un élément en particulier par [i,j] où i est le numéro de ligne et j le numéro de colonne
# comme pour les matrices en maths. SAUF que le prmier élément est indexé par zéro
print ('élément 0,0  vaut ',m0[0,0])
#on peut aussi accéder pour modifer
m0[2,3]=56
print('Le tableau m0 entier: deuxieme version\n ',m0)
# un tableau avec des 1
m1=np.ones((5,6))

print ("tableaux de m1:\n",m1)


Le tableau m0 entier: premiere version
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
élément 0,0  vaut  0.0
Le tableau m0 entier: deuxieme version
  [[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 56.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
tableaux de m1:
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


# Opérations élémentaires

lire le code ligne par ligne et prédire le résultat, puis exécuter.

1. Addition
2. Multiplication
3. Transposition
4. Multiplication matricielle
5. Inverse d'une matrice



In [ ]:
#somme
msomme=m1+m0
print ('la somme \n',msomme)
#multiplication point a point
mmult=m1*m0
print ('la multiplication\n',mmult)

#La transposition
mtranspose=m0.T
print ('la transposition de m0',mtranspose)
print ('en praticulier mtranspose[3,2]',mtranspose[3,2])
# A votre avis que va renvoyer m0[2,3] après cette  opération
mtranspose[3,2]=45
print ('m0 a été altéré par la modification de mtranspose',m0[2,3])

# pour eviter de modifer le tableau d'originie in faut le copier
mtransposesafe=(m0.copy()).T
mtransposesafe[4,3]=78
print ('m0 n''a pas été altéré par matransposesafe', m0[3,4])


In [ ]:
# La multiplication matricielle se note avec un @
# une seule des lignes suivante produira une erreur. Laquelle?  Commenter la ligne fautive avant d'excuter
print(m0@m1)
print(m1.T@m0)
print(m0@m1.T)

# Implémenter la TFD sous forme d'une multiplication matricielle
Pour un signal fini de taille N u_0...u_{N-1} la TFD de taille N donne N valeurs
uchapeau(k)= somme (pour n=0..N-1, exp(-2 i PI k/N n) u_n

On peut donc voir la TFD comme un opérateur linéaire de C^N dans C^N et donc une matrice carre dont la ligne numéro k (k commence à 0) vaut

exp(-2 i PI k/N n)
en python i s'écrit 1j

In [ ]:
#La fonction suivante et très peu efficace, elle sert juste de support pédagogique.
# Elle prend un tableau sous forme de ligne  et renvoie sa TFD de la taille correspondant
# à sa taille
def TFD(u):
  N=len(u) # len renvoie la longueur
  ns=np.arange(0,N,1) # renvoie 0,1,2...N-1
  ks=np.arange(0,N,1)
  # on transforme ks en une matrice colonne
  ks=ks.reshape((N,1))
  # les ns deviennent une matrice ligne
  ns=ns.reshape((1,N))
  # Le produit d'une colonne et d'une ligne fait une matrice carre
  # cette matrice va contenir k*n
  ksns=ks@ns
  # avant de prendre l'exponentielle on multiplie par -2 i PI /N
  ksns=-2*1j*pi/N*ksns
  # Enfin on a la matrice de la TFD
  MTFD=exp(ksns)
  # On applique cette matrice à l'entrée
  out=MTFD@(u.reshape((-1,1))) #le -1 signifie la velaur nécessaire pour utiliser toutes les données de u
  return out # on renvoie le résultat






In [ ]:
# Teste de la TFD
print('La TFD de taille 3 de (1,1,1):\n',TFD(np.ones((3))))
# faire la convolution circulaire de (1,2,3) avec (4,5,6) (taille 3) et expliquer le résultat suivant
tab123=np.zeros(3)
tab456=np.zeros(3)
tab123[0]=1
tab123[1]=2
tab123[2]=3

tab456[0]=4
tab456[1]=5
tab456[2]=6
# expliquer le résultat suivant (attention aux erreurs d'arrondi)
print('LA TFD de 31 31 28 moins le produit de la TFD de 1 2 3 par la TFD de 4 5 6\n',TFD(np.asarray([31,31,28]))-TFD(tab123)*TFD(tab456))


# Écoute d'un son d'une certaine fréquence
Le code suivant génère une note de musique à 440Hz
Puis la joue


In [ ]:
TFD=np.fft.fft # On utilise la TFD de python qui est beaucoup plus efficace
# EN particulier la TFD de'finie ci-dessus va planter avec une taille trop grande car elle génère explicitement une
# grand matrcie carrée

f0=440 # la frequence en Hz
duree=2 # la duree en seconde
Fe=44100 # on veut 44100 échantillons par seconde
temps=np.arange(0,Fe*duree)/Fe # les 88200 intervalles de temps en secondes
note=sin(2*pi*f0*temps)
joue_son(note)

In [ ]:
plt.plot(note[:400]) # on trace 400 echantillons de la note de musique



# Expliquer le resultat final de cette cellule

En particulier modifier et N et prédire la nouvelle valeur de K

In [ ]:
N=8000
morceau=note[0:N] # les N premier echantillons de la note
TFDmorceau=TFD(morceau).reshape((-1))# le reshape pour avoir un vecteur monodimensionnal  et non de la forme (N,1)
plt.plot(abs(TFDmorceau))
# la fonction argmax renvoie la position du maximum d'un tableau
K=(abs(TFDmorceau[:N//2])).argmax()# Pourquoi suffit-il de prendre la premiere moitiée (N//2)?
# expliquer la valeur de K
print ('le maximum de la TFD du morceau de taille 2000 a été trouvé en ',K)
print (K/N*Fe/f0)


# BONUS: La FFT: TFD en N log(N) au lieu de N^2

***Cette partie est facultative***

La fonction suivante calcule la TFD en utilisant l'algorithme de la Transformée de Fourier rapide (FFT en anglais). La fonction suivante se restreint aux tailles de signaux en puissance de 2 mais la FFT existe aussi pour (toutes) les tailles de signaux.

 L'algorithme basique de la TFD revient à appliquer une matrice NxN à un vecteur de taille N. La complexité en N^2

  La FFT a une complexité en N log(N).

  En effet si P est le polynome de degre N-1 dont les coefficients sont les u_n
  alors le cofficient k de la TFD vaut P(w^k) où w=exp(-2 i PI 1/N) est une racine primitive N-ieme de l'unite.

   La TFD consiste à évaluer P en toutes les racines N-iemes de l'unité.

  Or, si P(X)=Q(X^2)+X R(X^2) ou Q et R prennent les parties paires et impaire de P, on constate qu'il suffit de savoir évaluer Q et R aux racines N/2-ieme de l'unité pour ensuite retrouver P aux racines N-ieme en N opérations de reconstruction.

   Or calculer Q (ou R) aux racines N/2-iemes de l'unite est une TFD de taille N/2 (comme N est une puissance de 2, on est dans une recurssion directe.

   Le temps de calcul T(N) est
   T(N)=2T(N/2)+N

  On démontre que T est de l'ordre de N log(N) (log à base 2).


In [ ]:
def myfft(u):
  # on suppose que la taille est une puissance de 2 et on ne le vérifie pas.
  N=len(u)
  if N==1:
    return u.astype(np.complex128) #la TFD de taille 1 est l'identité
  else:
    out=(0*u).astype(np.complex128)
    Rpair=myfft(u[::2]) # les echantillons de 2 en 2 en commancant à 0
    Rimpair=myfft(u[1::2]) # idem en commancant à 1
    for k in range(N): # on parcourt les racines N-ieme
      pos=k%(N//2) # w^(2k) est la k-ieme racine N/2-ieme, il faut faire un modulo si on depasse N/2
      rack=exp(-2*1j*pi*k/N)
      out[k]=Rpair[pos]+rack*Rimpair[pos]
  return out

In [ ]:
N=128
t=np.random.randn(N)# valaurs aletoires
mafft=myfft(t) # notre algo de fft
fftsys=np.fft.fft(t) # fft du système
print (abs(mafft-fftsys).max()) # si le max de la difference est epsilonesque: Succes!